@rootURL = http://localhost:5045

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/Books
Accept: application/json

###
GET {{rootURL}}/api/Books/3
Accept: application/json

###
POST {{rootURL}}/api/Books
Content-Type: application/json

{
    "author": "A7",
    "title": "T7",
    "yearPublished": 2007
}

###
PUT {{rootURL}}/api/Books/1
Content-Type: application/json

{
    "id": 9,
    "author": "A9",
    "title": "T9",
    "yearPublished": 2009
}

###
DELETE {{rootURL}}/api/Books/1
Content-Type: application/json