// <auto-generated />
using APIone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIone.Migrations
{
    [DbContext(typeof(FirstAPIContext))]
    partial class FirstAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIone.models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "A1",
                            Title = "T1",
                            YearPublished = 2001
                        },
                        new
                        {
                            Id = 2,
                            Author = "A2",
                            Title = "T2",
                            YearPublished = 2002
                        },
                        new
                        {
                            Id = 3,
                            Author = "A3",
                            Title = "T3",
                            YearPublished = 2003
                        },
                        new
                        {
                            Id = 4,
                            Author = "A4",
                            Title = "T4",
                            YearPublished = 2004
                        },
                        new
                        {
                            Id = 5,
                            Author = "A5",
                            Title = "T5",
                            YearPublished = 2005
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
